import { createClient } from '@sanity/client'
import { createGroqBuilder, makeSafeQueryRunner } from 'groqd'

// Import Sanity types, generated by Sanity project.
import type * as SanityTypes from './sanity.types.ts'

const sanityClient = createClient({
  projectId: '0a9a4r26',
  dataset: 'production',
  useCdn: true,
  apiVersion: '2023-05-03',
  token: import.meta.env.VITE_DATABASE_API_KEY,
})

export const runQuery = makeSafeQueryRunner((query) =>
  sanityClient.fetch(query)
)

type SchemaConfig = {
  schemaTypes: SanityTypes.AllSanitySchemaTypes
  referenceSymbol: typeof SanityTypes.internalGroqTypeReferenceTo
}
export const q = createGroqBuilder<SchemaConfig>({})
